
// SPDX-License-Identifier: Apache-2.0.
//---------------------------------------------------------------------------//
// Copyright (c) 2022 Mikhail Komarov <nemo@nil.foundation>
// Copyright (c) 2022 Ilias Khairullin <ilias@nil.foundation>
// Copyright (c) 2022 Aleksei Moskvin <alalmoskvin@nil.foundation>
// Copyright (c) 2022-2023 Elena Tatuzova <e.tatuzova@nil.foundation>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//---------------------------------------------------------------------------//
pragma solidity >=0.8.4;

import '@nilfoundation/evm-placeholder-verification/contracts/types.sol';
import "./gate_argument.sol";

library mina_base_gate3{
    uint256 constant MODULUS_OFFSET = 0x0;
    uint256 constant THETA_OFFSET = 0x20;

    uint256 constant CONSTRAINT_EVAL_OFFSET = 0x00;
    uint256 constant GATE_EVAL_OFFSET = 0x20;
    uint256 constant GATES_EVALUATIONS_OFFSET = 0x40;
    uint256 constant THETA_ACC_OFFSET = 0x60;
    
	uint256 constant WITNESS_EVALUATIONS_OFFSET = 0x80;
	uint256 constant CONSTANT_EVALUATIONS_OFFSET = 0xa0;
	uint256 constant SELECTOR_EVALUATIONS_OFFSET = 0xc0;


    function evaluate_gate_be(
        types.gate_argument_params memory gate_params,
        mina_base_gate_argument_split_gen.local_vars_type memory local_vars
    ) external pure returns (uint256 gates_evaluation, uint256 theta_acc) {
        gates_evaluation = local_vars.gates_evaluation;
        theta_acc = local_vars.theta_acc;
        uint256 terms;
        assembly {
            let modulus := mload(gate_params)
            let theta := mload(add(gate_params, THETA_OFFSET))


            function get_witness_i_by_rotation_idx(idx, rot_idx, ptr) -> result {
                result := mload(
                    add(
                        add(mload(add(add(mload(add(ptr, WITNESS_EVALUATIONS_OFFSET)), 0x20), mul(0x20, idx))), 0x20),
                        mul(0x20, rot_idx)
                    )
                )
            }

            function get_constant_i(idx, ptr) -> result {
                result := mload(add(add(mload(add(ptr, CONSTANT_EVALUATIONS_OFFSET)), 0x20), mul(0x20, idx)))
            }

            function get_selector_i(idx, ptr) -> result {
                result := mload(add(add(mload(add(ptr, SELECTOR_EVALUATIONS_OFFSET)), 0x20), mul(0x20, idx)))
            }

			mstore(add(local_vars, GATE_EVAL_OFFSET), 0)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(3,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xb57260badff5653d7fde8ed417e16fa8bcaeca3ff415a361d690dcda1346c97
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(4,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x3686aa934c12341b0cc122df6b0ebbc4d6f7d237b19cb6c014c94964465d2327
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(5,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x15b2fd73f652c63cf9994874ba30522afaa736c2d1b0908126adce8686d8d9ad
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(6,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x33ce497097af4c428e01b17667b1d378e0f17500b45aaa52eabbede98feab4ce
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(7,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x25d835f46ac2c2459471fe30f828939f08257be86a1ef9c0d90943c8ab0d1271
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(8,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2f651683da29fdbd47928e96e692dded2fdddfa929739ee2619bc553facfce81
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(9,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x96736cd0d5e9084465453f7613d218658b0407a98c480b35c7ddd2257c5263d
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(10,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x381da1f537045c23ec9f07565605f4214437c6f92a3c483e16268ffcd521941
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(11,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x103afdc3a1b512a5582035f0ab6d0e49329b6862d33e2fbb75b81df8737a7588
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(12,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x13edb8ca0c06dbab904b0205d5fe71fc2d163528666479491372a3888125989c
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(13,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2d378a36486a6e5306fcc07493e1ca8efb824dd81604895cb853adac5cc7ddb0
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(14,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x3256ca176a7a82c658247b895125a5b0f29e79665f9f1dbc548bcef77aaad74
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(0,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x1e7148a905a0e2060e146dd107f4f7adc9bf1f54d2bebc1a8b3e1bda7ea278a8
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(1,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x1c430efcd6a8fea10e8e044bcd6435f3ca710076b71dd326e8aa8d1dcfe3043b
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(2,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x28b8b3c495643efa8209b461b29d45245a531280cb75a1547d0dcb8afa284316
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, GATE_EVAL_OFFSET),mulmod(mload(add(local_vars, GATE_EVAL_OFFSET)),get_selector_i(3,local_vars),modulus))
			gates_evaluation := addmod(gates_evaluation,mload(add(local_vars, GATE_EVAL_OFFSET)),modulus)
			mstore(add(local_vars, GATE_EVAL_OFFSET), 0)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(3,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x3e67d93f11dd68d214be8ba2c42bed3d74094ce3b5edadbacf44bfff005c2ab1
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(4,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xf434e82029dd3b90cd8a0967ce649729a2fda2bd2bf0bd83a57175a43bc1058
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(5,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x427e93deb399befdd63042e0b5c5bd1b837160848785e11dcb1e4e8d00d36b6
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(6,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x376bc13fe260460bc37bf8a88c76864edb82e22a712a78326eda481cba9cc160
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(7,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x198f4073fe7dd1ce38f689d9627612a765ccebcc6c2ec7d5b9a424f4674a81ba
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(8,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x322ac4bea665187242c197649a14335b8e569e671bd69a2cd1d323b14dfbf808
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(9,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x397e882d6ca7a1f4737189575a9a3797882910155f9d5189787226caac0dfc3e
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(10,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xade90b8efbc799123cdb5272730f3388f481eeb49c5adfcae66b5a7e294d30c
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(11,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2029104dac9401ee13c8c91808bb73fe371c3e6bc79100d56760acfefb9b0952
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(12,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x1367d38cadefdd7603e4b72503261c33ebf93eb8e4f59ad47752403deffcc39a
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(13,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xad08173899d27924638dd2b2f88877a9ad4e0c959f1433f5e1961587ae3e4bc
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(14,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x271c3f3e355a1c129911e5490aa5a37fbe6dcf4bd49eb14055e9dfa5eb61c82c
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(0,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x25642daf8a81d610b6a646410a64b19f403c42cb8be86733e1431140986386fe,get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x7b55f6050c5b78c81d29b095fcf55dbf3d93bb6ae6857e50278a679df3af934,get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d484fdf643cf7ff9b2a31b585fc9ac2a1233f549a628a5931b192e6193012c,get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xedb4ed214c82344c2693e5f72af8adc3f38951b77b79f5c6b8285c97bdd1523
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(1,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3611a838f43caeddf4ef867c503054417aae305760a767dd747585f94b40c5bf,get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1f67666943d65692e897b2c52b37a67ef131727cd42a9b9d7a92d598c95dba72,get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2b1c6524d1e8e51dcdee9be61180d9270927bb1363e9d68364b055783c4d1964,get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2bc40f210cebc814def6adff2d2bf9193cd420c8a10f61dadf6d6f7bcdea2367
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(2,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28babbca8497809a56a6f3e209de7e74cdf3c327c7f37e8763ae1fc9e9109836,get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x356d9c23e5e62e83040ea4fe9944da08c669ca8e81f47139c3efafcd3d3beca,get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x30e04108a2b549c4857ed07f484fc8c6f6a77299f927ccf4bc7af17f551eeb5,get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x214116debc0cd4b062656f529d47b7c38ad218858df931fc2d4e9da2710c70ea
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, GATE_EVAL_OFFSET),mulmod(mload(add(local_vars, GATE_EVAL_OFFSET)),get_selector_i(4,local_vars),modulus))
			gates_evaluation := addmod(gates_evaluation,mload(add(local_vars, GATE_EVAL_OFFSET)),modulus)

        }
    }
}
