name: Mina Placeholder verification tests

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true


jobs:
  test:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0

      - name: Install node dependencies
        run: |
          set -xe
          npm i

      - name: Run tests
        run: |
          set -eo pipefail
          npx hardhat test