
// SPDX-License-Identifier: Apache-2.0.
//---------------------------------------------------------------------------//
// Copyright (c) 2022 Mikhail Komarov <nemo@nil.foundation>
// Copyright (c) 2022 Ilias Khairullin <ilias@nil.foundation>
// Copyright (c) 2022 Aleksei Moskvin <alalmoskvin@nil.foundation>
// Copyright (c) 2022-2023 Elena Tatuzova <e.tatuzova@nil.foundation>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//---------------------------------------------------------------------------//
pragma solidity >=0.8.4;

import '@nilfoundation/evm-placeholder-verification/contracts/types.sol';
import "./gate_argument.sol";

library mina_scalar_gate8{
    uint256 constant MODULUS_OFFSET = 0x0;
    uint256 constant THETA_OFFSET = 0x20;

    uint256 constant CONSTRAINT_EVAL_OFFSET = 0x00;
    uint256 constant GATE_EVAL_OFFSET = 0x20;
    uint256 constant GATES_EVALUATIONS_OFFSET = 0x40;
    uint256 constant THETA_ACC_OFFSET = 0x60;
    
	uint256 constant WITNESS_EVALUATIONS_OFFSET = 0x80;
	uint256 constant CONSTANT_EVALUATIONS_OFFSET = 0xa0;
	uint256 constant SELECTOR_EVALUATIONS_OFFSET = 0xc0;


    function evaluate_gate_be(
        types.gate_argument_params memory gate_params,
        mina_scalar_gate_argument_split_gen.local_vars_type memory local_vars
    ) external pure returns (uint256 gates_evaluation, uint256 theta_acc) {
        gates_evaluation = local_vars.gates_evaluation;
        theta_acc = local_vars.theta_acc;
        uint256 terms;
        assembly {
            let modulus := mload(gate_params)
            let theta := mload(add(gate_params, THETA_OFFSET))


            function get_witness_i_by_rotation_idx(idx, rot_idx, ptr) -> result {
                result := mload(
                    add(
                        add(mload(add(add(mload(add(ptr, WITNESS_EVALUATIONS_OFFSET)), 0x20), mul(0x20, idx))), 0x20),
                        mul(0x20, rot_idx)
                    )
                )
            }

            function get_constant_i(idx, ptr) -> result {
                result := mload(add(add(mload(add(ptr, CONSTANT_EVALUATIONS_OFFSET)), 0x20), mul(0x20, idx)))
            }

            function get_selector_i(idx, ptr) -> result {
                result := mload(add(add(mload(add(ptr, SELECTOR_EVALUATIONS_OFFSET)), 0x20), mul(0x20, idx)))
            }

			mstore(add(local_vars, GATE_EVAL_OFFSET), 0)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(3,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x3a6f10d5eb45c31081706c59221b2b7f1cc93bf6c19db84a4a903262e63ff11b
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(4,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x388055881287007496a7a620cb24aea82b9207a58a3570b2fc789791f1a00192
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(5,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x1ab4836b6aa3766b12e91366af2a6537d7ce217efa55fa82421c25e145d21b1
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(6,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x8266e2372b21c6edcaa8ba38287074fdd2fe7aed8b215b8d0e91aab35f0f3e4
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(7,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x33f9eb22e3009397e8500f627d107d71a17babae697126ad0349e910df07e0f3
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(8,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x3ccca1cca5c012bb7bdca6ad74c1771e9ffc81be617ad0ef234102f212fabdbe
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(9,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x34ddfd55ab2bd0b0f896c8998dc469db5849f428cf6909f97d2a6a86ea5b75e4
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(10,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x16fdac1f1e2d38d4cd5a4d8dec85f76d6cb34df07a6df3e1665cea4ac58f1622
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(11,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x16678c18cfda283748e02df62ec2458814488e819134a3a52043c8c49c2ff0e
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(12,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x29b97d0aa13ceb09c60a07f9d5b220ee34c5c379e40306ad96f7b7136fe9a27c
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(13,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xf645def6c362fb37e42ad8c52ef9b1e64b631cadc623effb167765e14e2c200
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(14,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2a618d44fcf34766b4d153e2b1182f0fb73b8fcd9382d47d2bebad949f5d8b28
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(0,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x328bc240390c37cc31d10b6a94152c3f09496763a474706573433e8e6de7022b
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(1,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2734a56dcf148bfba1217cb53922ed644fa652ce3f77120c248d2d12e1695979
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(2,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x127d07a03ddd4dea6fd29e37a36974c6aca92ccd6ef3c7bdbbbe696151cee19b
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, GATE_EVAL_OFFSET),mulmod(mload(add(local_vars, GATE_EVAL_OFFSET)),get_selector_i(8,local_vars),modulus))
			gates_evaluation := addmod(gates_evaluation,mload(add(local_vars, GATE_EVAL_OFFSET)),modulus)
			mstore(add(local_vars, GATE_EVAL_OFFSET), 0)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(3,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x16df7d741a68d347007fdcc7956f57c86649ce624b70a7a59474d93448dade1b
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(4,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xefe88b1e3c28d2fef104d63e93b89169988e488e7e5695aabea215a4fc9f7ae
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(5,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(0,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(1,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(2,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0xd84b19cac3f661be5700546efc669464fa99121fa7a8fc2e54b95608df390ad
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(6,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x3f8e3d6fe722b72a3aa8c861562b502816b4206d348ada06d18270bb4574b8a5
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(7,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x1a10211093a52a97cb4db301fc2a8c9f6e133a3306cd19f457b83052548d9fc9
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(8,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(3,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(4,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(5,1, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2f6001a326e70328258024bf2cd53bf92df311ac2f518ca7c263951f4308f718
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(9,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x20b21a2874bc871f135b6126b666274390fdf94e0c0b3c528c8c443e9ab2e742
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(10,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x28ce7a1e1552f99b45e3fe471be85bbdf623f4bea7684ae40035a302dfa1b663
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(11,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(6,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(7,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(8,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x29e5f174ce5902bd8d823f5c851b08eaba0ba5a395d770f5fe363f55f1de0544
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(12,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x21354c0bd6cb5339bb33dd8cea13294535efa9e76b840756850dcb6c3bf5834
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(13,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x1628abe2d5b03206380ebb31e16a85a1c5d93bf5c37c677574763de78f74d7fa
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(14,0, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(9,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(10,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(11,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x22fadaaa797a6882cde01793fa0b9d51f3effa8ee968d317613ed5eefbabeeb7
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(0,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x1d70822e80b8581cfb5ab2c8822851174db06f98c33edea8c227e30dc22a6b3,get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0xf24f954496903346d4d753deb0b76c2e26e4dbebf04906842d108dc883cda01,get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x28beef43e4fa739fe900a17ead54c004b4182caf07ae3e235c20915be480a9c7,get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x3d82e513f3337f08e2f62d563f48911a23ac11aa9a863fc2ece730eaf34860cf
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(1,2, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x2d2c9057cafceb967f3fa5e2b7432af2f3a9556b26410784eb48b2a2d4b514f5,get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x154e83714c9641589160f3c7a17450390d0fda1f7b8dd86db5ead4b016b263ac,get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3f336eacd7e9a3ec67950ed81ef7461a48a08c9e40666a67558e2746a4b57aca,get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x23d71297ea61ab207d6919ab4f3e4a78f46283a451e47e0166d91f0affdd6459
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET), 0)
			terms:=get_witness_i_by_rotation_idx(2,1, local_vars)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3b26592d8f96997714bcb9eac4c7f39ee808ce0b0e3a8a5a0c0650405ebc2ce6,get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(12,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x3d57fa111cce837451e082ea541b2d8033e6ed2c6f61740c012db87dc88b3cdd,get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(13,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=mulmod(0x264f6d16392002e14e4920d243ff44dd9e8cf174e256dd2ff0b96153afd48444,get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			terms:=mulmod(terms, get_witness_i_by_rotation_idx(14,0, local_vars), modulus)
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			terms:=0x2a36341d640b1827451dd22ddec3798dd3ad5411bdf67427242b0005f68ddea3
			mstore(add(local_vars, CONSTRAINT_EVAL_OFFSET),addmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),terms,modulus))
			mstore(add(local_vars, GATE_EVAL_OFFSET),addmod(mload(add(local_vars, GATE_EVAL_OFFSET)),mulmod(mload(add(local_vars, CONSTRAINT_EVAL_OFFSET)),theta_acc,modulus),modulus))
			theta_acc := mulmod(theta_acc, theta, modulus)
			mstore(add(local_vars, GATE_EVAL_OFFSET),mulmod(mload(add(local_vars, GATE_EVAL_OFFSET)),get_selector_i(9,local_vars),modulus))
			gates_evaluation := addmod(gates_evaluation,mload(add(local_vars, GATE_EVAL_OFFSET)),modulus)

        }
    }
}
